# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- azure-pipelines

variables:
  - group: MealMastermindEnv

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: Build_and_Test
        displayName: 'Build and Test'
        steps:
          - task: Npm@1
            inputs:
              command: 'install'
            displayName: 'Install NPM'
          - task: Npm@1
            inputs:
              command: 'custom'
              customCommand: 'run build'
            displayName: 'Compile Project'
          - task: Npm@1
            inputs:
              command: 'custom'
              customCommand: 'run test -- --coverage --coverageReporters="json-summary" --outputFile=coverage/coverage-summary.json'
            displayName: 'Run Unit Tests and Generate Coverage Report'
            continueOnError: false

  - stage: Deliver
    jobs:
      - job: Package_Artifact
        displayName: 'Package Artifact'
        steps:
          - script: |
              npm install
              npm run build
              tar -czf build.tar.gz .next/
            displayName: 'Package Build Artifacts'
            
  - stage: Deploy_to_Dev
    jobs:
      - deployment: Deploy
        displayName: 'Deploy to Development'
        environment: 'development'
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo "Deploying to Development"
                    echo "Deploy completed to DEV"
                  displayName: 'Deploy Application'

  - stage: Deploy_to_QAT
    jobs:
      - deployment: Deploy
        displayName: 'Deploy to QAT'
        environment: 'QAT'
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo "Deploying to QAT"
                    echo "Deploy completed to QAT"
                  displayName: 'Deploy Application'

  - stage: Deploy_to_Staging
    jobs:
      - deployment: Deploy
        displayName: 'Deploy to Staging'
        environment: 'staging'
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo "Deploying to Stage"
                    echo "Deploy completed to Stage"
                  displayName: 'Deploy Application'

  - stage: Deploy_to_Production
    jobs:
      - deployment: Deploy
        displayName: 'Deploy to Production'
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo "Deploying to Production"
                    echo "Deploy completed to Production"
                  displayName: 'Deploy Application'